### ISSUE TITLE
Repetitive code, could be streamlined.

### ISSUE THREAD

**Issue by EEdLoh** [pshowell23/rpg-tool#1]
All those die functions are the same. What's up with that? It seems like it would be more flexible and easier to maintain if you just made the roller function pass its parameter to the RNG. If you want to restrict the roller to only certain numbers you can put in a [multiple case value switch](https://www.geeksforgeeks.org/golang-program-that-uses-switch-multiple-value-cases/) and just have it either roll the di(c)e or panic/error/give a warning message.

**Comment by pshowell23** [comment]
Honestly, I think I wrote it that was cause I was into playing with switches in golang. But it could definitely be streamlined.

**Comment by pshowell23** [comment]
Decided to go the route of just letting the user determine how many sides the die should have. In the future, this will have a front end and that will determine what die gets rolled anyway.

Sooooooooo better?

**Comment by EEdLoh** [comment]
I was thinking you could maintain your restriction with a multi-value switch. Something like:
```golang
func Roller(n int) int {
    switch; n {
        case 2, 3, 4, 6, 8, 12, 20, 100: return rollDie(n)
        default: return 0 //could be a panic or warning message or whatever
    }
}
```

My go might be a bit rusty but I think the idea stands. Lol.

**Comment by pshowell23** [comment]
#2 Apparently IDK how GitHub works like this, but I think I made an acceptable change

**Comment by EEdLoh** [comment]
Seems legit!

**Comment by pshowell23** [comment]
Done!
